services:
  postgres_cybercare:
    container_name: postgres_cybercare
    image: postgres:15
    env_file: .env
    shm_size: 10g
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    restart: always
volumes:
  db:
